version: "3.8"

services:
  commondb:
    image: mcr.microsoft.com/mssql/server
    container_name: commondb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin@123
    restart: always
    ports:
      - "1433:1433"
    networks:
      - microservices_network

  distributedcache:
    image: redis:latest
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - microservices_network

  messagebroker:
    image: rabbitmq:management
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
    name: microservices_network
