# Use the official Node.js image as a base
FROM node:18

# Set the working directory in the container
WORKDIR /react-app

# Copy package.json and package-lock.json first for dependency installation
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application's source code into the container
COPY . .

# Expose the port that the app will run on
EXPOSE 3000

# Start the app
CMD ["npm", "start"]
