
FROM node:18 AS build

WORKDIR /app

WORKDIR /react-app

COPY package*.json ./

RUN npm install


COPY . ./
RUN npm run build
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 3000


CMD ["npm", "start"]
