
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ENV applicationUrl="https://localhost:7122"
ENV ASPNETCORE_ENVIRONMENT="Development"
EXPOSE 5000
WORKDIR /app

COPY . .
RUN dotnet restore

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app

COPY --from=build /app .

ENTRYPOINT ["dotnet", "MultiDatabase.dll"]
