
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /multiDatabase


COPY . .
RUN dotnet restore


RUN dotnet publish -c Release -o /app


FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app


COPY --from=build /app .


EXPOSE 7122


ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=https://localhost:7122


ENTRYPOINT ["dotnet", "MultiDatabase.dll"]
