
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ENV applicationUrl="https://localhost:7122"
ENV ASPNETCORE_ENVIRONMENT="Development"
EXPOSE 7122
WORKDIR /multiDatabase

COPY . .
RUN dotnet restore

RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app

COPY --from=build /app .
CMD [“/bin/bash”, “-c”, “dotnet restore && dotnet run”]
ENTRYPOINT ["dotnet", "MultiDatabase.dll"]
