# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  multidatabase:
    image: multidatabase
    build:
      context: .
      dockerfile: MultiDatabase/Dockerfile
    ports:
      - 7122:7122
