// <auto-generated />
using System;
using Catalog.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.API.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5334c996-8457-4cf0-815c-ed2b77c4ff61"),
                            Category = "[\"Smart Phone\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            ImageFile = "product-1.png",
                            Name = "IPhone X",
                            Price = 950.00m
                        },
                        new
                        {
                            Id = new Guid("c67d6323-e8b1-4bdf-9a75-b0d0d2e7e914"),
                            Category = "[\"Smart Phone\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            ImageFile = "product-2.png",
                            Name = "Samsung 10",
                            Price = 840.00m
                        },
                        new
                        {
                            Id = new Guid("4f136e9f-ff8c-4c1f-9a33-d12f689bdab8"),
                            Category = "[\"White Appliances\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            ImageFile = "product-3.png",
                            Name = "Huawei Plus",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = new Guid("6ec1297b-ec0a-4aa1-be25-6726e3b51a27"),
                            Category = "[\"White Appliances\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            ImageFile = "product-4.png",
                            Name = "Xiaomi Mi 9",
                            Price = 470.00m
                        },
                        new
                        {
                            Id = new Guid("b786103d-c621-4f5a-b498-23452610f88c"),
                            Category = "[\"Smart Phone\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            ImageFile = "product-5.png",
                            Name = "HTC U11+ Plus",
                            Price = 380.00m
                        },
                        new
                        {
                            Id = new Guid("c4bbc4a2-4555-45d8-97cc-2a99b2167bff"),
                            Category = "[\"Home Kitchen\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            ImageFile = "product-6.png",
                            Name = "LG G7 ThinQ",
                            Price = 240.00m
                        },
                        new
                        {
                            Id = new Guid("93170c85-7795-489c-8e8f-7dcf3b4f4188"),
                            Category = "[\"Camera\"]",
                            Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.",
                            ImageFile = "product-6.png",
                            Name = "Panasonic Lumix",
                            Price = 240.00m
                        },
                        new
                        {
                            Id = new Guid("72a9b04e-9d2a-47c3-9f6f-b396e17b1fe3"),
                            Category = "[\"Laptop\",\"Electronics\"]",
                            Description = "The latest MacBook Pro, featuring Apple's M1 chip for incredible performance.",
                            ImageFile = "product-7.png",
                            Name = "MacBook Pro 16\"",
                            Price = 2200.00m
                        },
                        new
                        {
                            Id = new Guid("e2f0c575-49f7-47fe-b935-59c0e9e9a4fd"),
                            Category = "[\"Laptop\",\"Electronics\"]",
                            Description = "A slim and powerful ultrabook with a high-definition screen.",
                            ImageFile = "product-8.png",
                            Name = "Dell XPS 13",
                            Price = 1500.00m
                        },
                        new
                        {
                            Id = new Guid("dbc8d8e9-9a69-4204-810b-2bc9cd351702"),
                            Category = "[\"Tablet\",\"Electronics\"]",
                            Description = "The 12.9-inch iPad Pro features a Liquid Retina display and is perfect for creative professionals.",
                            ImageFile = "product-9.png",
                            Name = "Apple iPad Pro 12.9\"",
                            Price = 1100.00m
                        },
                        new
                        {
                            Id = new Guid("1a5d52a2-7c21-43d0-a764-cf3f2325703d"),
                            Category = "[\"Tablet\",\"Electronics\"]",
                            Description = "Samsung's premium tablet, perfect for work and play.",
                            ImageFile = "product-10.png",
                            Name = "Samsung Galaxy Tab S7",
                            Price = 800.00m
                        },
                        new
                        {
                            Id = new Guid("d2e907b2-b321-4195-8c7a-b9f7e2c88d56"),
                            Category = "[\"Wearable\",\"Electronics\"]",
                            Description = "The latest smartwatch from Apple, offering enhanced health tracking and faster charging.",
                            ImageFile = "product-11.png",
                            Name = "Apple Watch Series 7",
                            Price = 399.00m
                        },
                        new
                        {
                            Id = new Guid("c06ec38f-70b1-4727-b94d-ff10db8a1bb3"),
                            Category = "[\"Wearable\",\"Health \\u0026 Fitness\"]",
                            Description = "Track your fitness and health with the Fitbit Charge 5.",
                            ImageFile = "product-12.png",
                            Name = "Fitbit Charge 5",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = new Guid("2a3f206f-0fd7-44b6-939b-9351c9c9843c"),
                            Category = "[\"Accessories\",\"Electronics\"]",
                            Description = "A high-performance wireless mouse designed for professionals.",
                            ImageFile = "product-13.png",
                            Name = "Logitech MX Master 3 Mouse",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = new Guid("728b6297-7d24-466d-bb74-8c4099f67655"),
                            Category = "[\"Accessories\",\"Audio\"]",
                            Description = "Wireless noise-canceling headphones with world-class sound quality.",
                            ImageFile = "product-14.png",
                            Name = "Bose QuietComfort 35 II",
                            Price = 299.00m
                        },
                        new
                        {
                            Id = new Guid("53fcd7d7-5e4a-47e5-bd84-eec179ea2429"),
                            Category = "[\"Accessories\",\"Audio\"]",
                            Description = "Industry-leading noise-canceling headphones from Sony.",
                            ImageFile = "product-15.png",
                            Name = "Sony WH-1000XM4",
                            Price = 350.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
