# Stage 1: Build the React App
FROM node:20 AS build

# Set the working directory
WORKDIR /reacts

COPY "./MultiDataBase Frontend/react-app/package.json" ./
COPY "./MultiDataBase Frontend/react-app/package-lock.json" ./

RUN npm install

COPY "./MultiDataBase Frontend/react-app/" ./

RUN npm run build
