
FROM node:20

WORKDIR /reacts

COPY "./MultiDataBase Frontend/react-app/package.json" ./
COPY "./MultiDataBase Frontend/react-app/package-lock.json" ./

RUN npm install


COPY "./MultiDataBase Frontend/react-app/" ./

EXPOSE 3000

# Run the React app in development mode
CMD ["npm", "run", "start"]
