# Use the Node.js image for development
FROM node:20

# Set the working directory
WORKDIR /reacts

# Copy package.json and package-lock.json to install dependencies
COPY "./MultiDataBase Frontend/react-app/package.json" ./
COPY "./MultiDataBase Frontend/react-app/package-lock.json" ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY "./MultiDataBase Frontend/react-app/" ./

# Expose the port React runs on in development
EXPOSE 3000

# Run the React app in development mode
CMD ["npm", "run", "start"]
