
FROM node:20

WORKDIR /reacts

COPY "./MultiDataBase Frontend/react-app/package.json" ./
COPY "./MultiDataBase Frontend/react-app/package-lock.json" ./

RUN npm install

# Copy the rest of the application code
COPY "./MultiDataBase Frontend/react-app/" ./

# Expose the port React runs on in development
EXPOSE 3000

# Run the React app in development mode
CMD ["npm", "run", "start"]
