
FROM node:20 AS build

WORKDIR /reacts

FROM node:20 AS build


WORKDIR /reacts

COPY ./MultiDataBase\ Frontend/react-app/package.json ./
COPY ./MultiDataBase\ Frontend/react-app/package-lock.json ./


RUN npm install

COPY ./MultiDataBase\ Frontend/react-app/ ./

RUN npm run build


FROM node:20 AS production

RUN npm install -g serve

COPY --from=build /reacts/build /app

EXPOSE 3000

CMD ["serve", "-s", "/app", "-l", "3000"]
tely for dependency caching
COPY ./MultiDataBase Frontend/react-app/package.json ./
COPY ./MultiDataBase Frontend/react-app/package-lock.json ./

RUN npm install

COPY ./MultiDataBase Frontend/react-app/ ./

RUN npm run build

