
FROM node:20 AS build

WORKDIR /reacts



WORKDIR /reacts

COPY ./MultiDataBase\ Frontend/react-app/package.json ./
COPY ./MultiDataBase\ Frontend/react-app/package-lock.json ./


RUN npm install

COPY ./MultiDataBase\ Frontend/react-app/ ./

RUN npm run build
