services:
  commondb:
    image: mcr.microsoft.com/mssql/server
  # catalogdb:
  #   image: mcr.microsoft.com/mssql/server
  # basketdb:
  #   image: mcr.microsoft.com/mssql/server
  # orderdb:
  #   image: mcr.microsoft.com/mssql/server
  distributedcache:
    image: redis
    
  messagebroker:
    image: rabbitmq:management
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: APiGateway/YarpAPIGateway/Dockerfile

# volumes:
  # sqlserver_commondb:
  # sqlserver_order:
  # sqlserver_catalog:
  # sqlserver_basket:
    

   





