
FROM node:20

WORKDIR /reacts
# C:\testing\Trainings\Muskan\MultiDatabase with DbContextFactory\MultiDataBase-Frontend\react-app\package.json
COPY ./MultiDataBase-Frontend/react-app/package.json ./package.json
COPY ./MultiDataBase-Frontend/react-app/package-lock.json ./




RUN npm install


EXPOSE 3000


CMD ["npm", "run", "start"]
