# FROM node:20

# WORKDIR /reacts
# COPY "./MultiDataBase-Frontend/react-app/package.json" ./reacts/package.json
# COPY "./MultiDataBase-Frontend/react-app/package-lock.json" ./reacts/package-lock.json
# RUN npm install

# EXPOSE 3000


# CMD ["npm", "run", "start"]
FROM node:20

# Set working directory to /reacts within the container
WORKDIR /reacts

# Copy package.json and package-lock.json directly as they are in the same directory as Dockerfile
COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm install

# Copy all other files (including source code) in the current directory to /reacts
COPY . .

# Expose the development server port
EXPOSE 3000

# Start the development server
CMD ["npm", "run", "start"]

