
FROM node:20

WORKDIR /reacts

COPY ./MultiDataBase-Frontend/react-app/package.json ./
COPY ./MultiDataBase-Frontend/react-app/package-lock.json ./




RUN npm install


EXPOSE 3000


CMD ["npm", "run", "start"]
